### ISSUE TITLE
stix-shifter does not install correctly via pip

### ISSUE THREAD

**Issue by nschwane** [opencybersecurityalliance/stix-shifter#400]
**Describe the bug**
stix-shifter does not install correctly via the recommended approach with pip. Using it results in `ModuleNotFoundError: No module named 'stix_shifter_utils'`.

**To Reproduce**
1. Create new virtualenv: `$ mkvirtualenv shifter --python=/usr/local/bin/python3.7`
2. Install stix-shifter with pip: `$ pip install stix-shifter`
3. Execute example: `$ stix-shifter translate qradar query {} "[ipv4-addr:value = '127.0.0.1']" {}`
5. Use as library: `>>> from stix_shifter.stix_translation import stix_translation`
6. See error

**Expected behavior**
Examples from the documentation should work without error.

**Error Message**
```
$ stix-shifter translate qradar query {} "[ipv4-addr:value = '127.0.0.1']" {}
Traceback (most recent call last):
  File "***/.virtualenvs/shifter/bin/stix-shifter", line 5, in <module>
    from stix_shifter.scripts.stix_shifter import main
  File "***/.virtualenvs/shifter/lib/python3.7/site-packages/stix_shifter/scripts/stix_shifter.py", line 3, in <module>
    from stix_shifter.stix_translation import stix_translation
  File "***/.virtualenvs/shifter/lib/python3.7/site-packages/stix_shifter/stix_translation/stix_translation.py", line 2, in <module>
    from stix_shifter_utils.stix_translation.src.patterns.parser import generate_query
ModuleNotFoundError: No module named 'stix_shifter_utils'
```

**Comment by delliott90** [comment]
Doing a `pip install stix-shifter-utils` should address the problem for now, but we need to look at the documentation to make sure this is addressed.

**Comment by nschwane** [comment]
That does install stix-shifter-utils, but the example still doesn't work because of another error:
```
$ stix-shifter translate qradar query {} "[ipv4-addr:value = '127.0.0.1']" {}
 2020-08-20 08:01:49,541 stix_shifter.scripts.stix_shifter ERROR    Module qradar not found
usage: stix-shifter [-h] {translate,mapping,transmit,execute,host} ...
...
```
